# -*- coding: utf-8 -*-
"""Rede_Neural_classificacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmFRZwUTPpmyCjyoOP5x30PgshBtxJa-
"""

# 1. Importação de bibliotecas

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)

# 1. Carregar DataFrame

def carregar_dataframe(path):
    return pd.read_csv(path)

# 2. Preparar DataFrame

def preparar_dataframe(df):
    """
    Prepara os dados:
    - cria coluna aprovado
    - separa X e y
    - identifica colunas numéricas e categóricas
    """
    df["aprovado"] = (df["G3"] >= 10).astype(int)

    X = df.drop("aprovado", axis=1)
    y = df["aprovado"]

    numericas = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
    categoricas = X.select_dtypes(include=["object"]).columns.tolist()

    return X, y, numericas, categoricas

# 3. Criar pipeline do modelo

def criar_modelo(numericas, categoricas):

    preprocess = ColumnTransformer(
        transformers=[
            ("num", StandardScaler(), numericas),
            ("cat", OneHotEncoder(handle_unknown="ignore"), categoricas)
        ]
    )

    mlp = MLPClassifier(
        hidden_layer_sizes=(64, 32),
        activation="relu",
        max_iter=1500,
        random_state=42
    )

    modelo = Pipeline([
        ("preprocessamento", preprocess),
        ("mlp", mlp)
    ])

    return modelo

# 4. Avaliar modelo

def avaliar_modelo(modelo, X_test, y_test):

    y_pred = modelo.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print("ACURÁCIA: {:.2f}%".format(acc * 100))
    print("PRECISÃO: {:.2f}%".format(prec * 100))
    print("RECALL: {:.2f}%".format(rec * 100))
    print("F1-SCORE: {:.2f}%".format(f1 * 100))

    print("\nRELATÓRIO DE CLASSIFICAÇÃO:")
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(6,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title("Matriz de Confusão")
    plt.xlabel("Previsto")
    plt.ylabel("Real")
    plt.show()

# 5. Adicionar probabilidade no DataFrame

def adicionar_probabilidade(modelo, df):
    X = df.drop("aprovado", axis=1)
    df["probabilidade_aprovacao"] = (modelo.predict_proba(X)[:, 1] * 100).round(2)
    return df

# 6. Execução da rede neural base de notas matematica


# 1) carregar dados
df = carregar_dataframe("Maths.csv")

# 2) preparar dados
X, y, numericas, categoricas = preparar_dataframe(df)

# 3) criar modelo
modelo = criar_modelo(numericas, categoricas)

# 4) dividir treino e teste
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.2, random_state=42
)

# 5) treinar
modelo.fit(X_train, y_train)

# 6) avaliar
avaliar_modelo(modelo, X_test, y_test)

# 7. Execução da rede neural base de notas matematica


# 1) carregar dados
df_math = carregar_dataframe("Portuguese.csv")

# 2) preparar dados
X, y, numericas, categoricas = preparar_dataframe(df)

# 3) criar modelo
modelo = criar_modelo(numericas, categoricas)

# 4) dividir treino e teste
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.2, random_state=42
)

# 5) treinar
modelo.fit(X_train, y_train)

# 6) avaliar
avaliar_modelo(modelo, X_test, y_test)